import { Button } from "@/components/ui/button"

export default function Home() {
  return (
    <div>
      <Button>Click me</Button>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque vel accusamus sed corporis commodi aspernatur et tenetur nisi fugiat nulla maiores voluptatem, ducimus, provident eveniet recusandae laudantium fuga alias expedita corrupti assumenda atque harum obcaecati. Optio odio architecto a deserunt laboriosam iure, error neque, amet ducimus, excepturi numquam tempora voluptates dolorum voluptas doloremque nihil quasi. Quis non corporis perferendis veritatis officia fuga expedita rerum soluta nam nihil? Corrupti ipsam tenetur, totam blanditiis reprehenderit fuga doloremque excepturi et quo at? Officia, eaque, animi consequatur consectetur non quisquam quod fugit aspernatur voluptatibus natus provident explicabo eos debitis. Eum hic quisquam, ad libero provident ratione quod veritatis alias minus quis ex at autem necessitatibus aperiam assumenda quas voluptates nobis aspernatur aliquid est fugit consequuntur nulla atque tempore. Modi voluptatem vitae, voluptatum error optio assumenda ut, quas voluptas dolorem non magni, minus deleniti voluptates possimus voluptate praesentium quisquam sit nobis. Facilis incidunt quod, iure et aliquam iusto. Inventore, numquam. Consectetur consequuntur, ullam doloribus aliquam aliquid non earum voluptas cumque molestias unde temporibus quae explicabo fugiat praesentium eos repudiandae necessitatibus qui modi quis aut provident, error veritatis est. Eveniet voluptas quas in cumque, earum praesentium quisquam, inventore, labore aliquid ea dolores? Explicabo ratione, provident soluta accusamus assumenda consequuntur corporis eligendi veritatis, facere, aspernatur molestias! Quam maiores cupiditate amet quo libero commodi nobis magnam accusantium id. Et eaque praesentium sint accusamus magnam fugit qui libero velit minus exercitationem fuga, ipsam modi nulla esse dolores voluptatem porro molestiae illo laudantium placeat sed vitae. Neque maxime doloribus ipsam consequatur a quae rem illum esse molestias, nam repudiandae, debitis commodi! Sunt velit obcaecati nisi et possimus odio numquam, nostrum ratione. Odit neque dolor aperiam ratione nemo, optio minima eum aspernatur non itaque fugit officiis corporis quaerat placeat! Sapiente aut, vel delectus officia soluta hic aperiam fugit omnis porro rem natus voluptas? Sed, unde! Doloribus et necessitatibus dolorum quibusdam numquam nam itaque. Quaerat, eligendi amet doloremque animi provident recusandae laudantium culpa accusamus officiis quae, sequi dignissimos fuga repudiandae. Aliquam inventore dolor corrupti placeat!</h1>
    </div>
  )
}
